export const NAV_ITEMS = [
  { label: "Dashboard", href: "/dashboard" },
  { label: "Banners", href: "/dashboard/banners" },
  { label: "Featured Layout", href: "/dashboard/featured-layout" },
  { label: "Tour Categories", href: "/dashboard/categories" },
  { label: "Destinations", href: "/dashboard/destinations" },
  { label: "Addons", href: "/dashboard/addons" },
  { label: "Product Tags", href: "/dashboard/tags" },
  { label: "Products", href: "/dashboard/products" },
  { label: "Blog", href: "/dashboard/blogs" },
  { label: "Blog Categories", href: "/dashboard/blogs/categories" },
  { label: "Gallery", href: "/dashboard/gallery" },
  { label: "Reviews", href: "/dashboard/reviews" },
  { label: "Coupons", href: "/dashboard/coupons" },
  { label: "Bookings", href: "/dashboard/bookings" },
  { label: "Inquiries", href: "/dashboard/inquiries" },
  { label: "Users", href: "/dashboard/users" },
  { label: "Settings", href: "/dashboard/settings" },
];
